# @package _global_
defaults:
    - override /hydra/sweeper: optuna
    - override /hydra/sweeper/sampler: tpe

learning_rate: 0.005
patience: 10
batch_size: 16
epochs: 30
scheduler:
    enable: true
    epochs: 30
device: "cuda:0"
label_smoothing: true
optimize: "weighted f1"
pretrained_model: "german-nlp-group/electra-base-german-uncased"
loss_report_frequency: 1000
optimize_outputs: ["event_kind"] # optionally add any of ["thought_representation", "mental", "iterative", "speech"]
dynamic_loss_weighting: False
static_loss_weights: [1.0]
dataset:
    excluded_collections: []
    kind: "json" # choice of json or catma
    catma_uuid: "CATMA_DD5E9DF1-0F5C-4FBD-B333-D507976CA3C7_EvENT_root"
    catma_dir: "."
    in_distribution: true
    special_tokens: true

hydra:
  sweeper:
      sampler:
          seed: 123
      direction: maximize
      study_name: first_try
      storage: null
      n_trials: 20
      n_jobs: 1

      search_space:
          learning_rate:
              type: float
              low: 1e-6
              high: 1e-3
              log: true
          'dataset.excluded_collections':
              type: categorical
              choices:
                  - ["Verwandlung_*"]
                  - ["Effi_Briest_*"]
                  - ["Eckbert_*"]
                  - ["Judenbuche_*"]
                  - ["Krambambuli_*"]
                  - ["Erdbeben_*"]
